### ISSUE TITLE
Looks good. Reminds me of Zipline

### ISSUE THREAD

**Issue by ItsNoted** [hanzydev/Fileship#4]
Is this not just a fork of Zipline? https://github.com/diced/zipline

Either way, I like what you did with the notes and code snippets. Any plans to incorporate ShareX support?

**Comment by hanzydev** [comment]
No, it's not a fork. The code is completely mine. As for ShareX support, it already exists, you can create a configuration for ShareX from the account management page. Also, I'm glad you like my project.

**Comment by diced** [comment]
I do get that this is a fork, but no offense- it looks awfully similar to Zipline, it doesn't hurt to say that it's inspired lol.
