### ISSUE TITLE
Codes with password creates issue

### ISSUE THREAD

**Issue by ItsNoted** [hanzydev/Fileship#5]
### Reproduction

The first code I added has a password for testing.

### Describe the bug

Then every other code I added had the same password shared.

### Additional context

This causes issues where I cannot remove or delete codes added and every code shares the same password created on the first one created.

**Comment by hanzydev** [comment]
I've created codes that share the same password and haven't encountered the issue of being unable to delete them. If you're experiencing this bug, please provide screenshots and logs from both the browser and server console. This will help me assist you more effectively.
